In [1]:
import sys
import pandas as pd
import numpy as np

# Task 1

In [55]:
df = pd.read_csv('/Users/matveyspiridonov/Downloads/_ea07570741a3ec966e284208f588e50e_titanic.csv')

In [56]:
df

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [4]:
df['Sex'].value_counts()

male      577
female    314
Name: Sex, dtype: int64

In [8]:
df[df['Survived'] == 1].shape[0] / df.shape[0]

0.3838383838383838

In [9]:
df[df['Pclass'] == 1].shape[0] / df.shape[0]

0.24242424242424243

In [15]:
df.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

In [17]:
df.corr()

PassengerId  Survived    Pclass       Age     SibSp     Parch  \
PassengerId     1.000000 -0.005007 -0.035144  0.036847 -0.057527 -0.001652   
Survived       -0.005007  1.000000 -0.338481 -0.077221 -0.035322  0.081629   
Pclass         -0.035144 -0.338481  1.000000 -0.369226  0.083081  0.018443   
Age             0.036847 -0.077221 -0.369226  1.000000 -0.308247 -0.189119   
SibSp          -0.057527 -0.035322  0.083081 -0.308247  1.000000  0.414838   
Parch          -0.001652  0.081629  0.018443 -0.189119  0.414838  1.000000   
Fare            0.012658  0.257307 -0.549500  0.096067  0.159651  0.216225   

                 Fare  
PassengerId  0.012658  
Survived     0.257307  
Pclass      -0.549500  
Age          0.096067  
SibSp        0.159651  
Parch        0.216225  
Fare         1.000000

In [32]:
df[df['Sex'] == 'female']['Name'].apply(lambda x: x.split()[2]).value_counts()

William      13
Anna          9
Mary          9
Thomas        6
Elizabeth     6
             ..
Elina         1
Mara          1
Gladys        1
Karl          1
Richard       1
Name: Name, Length: 202, dtype: int64

# Task 2

In [60]:
df1 = df[['Pclass','Age','Fare','Sex','Survived']]
df1 = df1.dropna()
df1

Pclass   Age     Fare     Sex  Survived
0         3  22.0   7.2500    male         0
1         1  38.0  71.2833  female         1
2         3  26.0   7.9250  female         1
3         1  35.0  53.1000  female         1
4         3  35.0   8.0500    male         0
..      ...   ...      ...     ...       ...
885       3  39.0  29.1250  female         0
886       2  27.0  13.0000    male         0
887       1  19.0  30.0000  female         1
889       1  26.0  30.0000    male         1
890       3  32.0   7.7500    male         0

[714 rows x 5 columns]

In [61]:
y = df1['Survived']
X = df1.drop('Survived', axis = 1)

In [64]:
X['Sex'] = X['Sex'].apply(lambda x: 1 if x == 'male' else 0)

In [65]:
X

Pclass   Age     Fare  Sex
0         3  22.0   7.2500    1
1         1  38.0  71.2833    0
2         3  26.0   7.9250    0
3         1  35.0  53.1000    0
4         3  35.0   8.0500    1
..      ...   ...      ...  ...
885       3  39.0  29.1250    0
886       2  27.0  13.0000    1
887       1  19.0  30.0000    0
889       1  26.0  30.0000    1
890       3  32.0   7.7500    1

[714 rows x 4 columns]

In [66]:
from sklearn.tree import DecisionTreeClassifier

In [67]:
model = DecisionTreeClassifier(random_state=241)
model.fit(X,y)

DecisionTreeClassifier(random_state=241)

In [68]:
model.feature_importances_

array([0.13700004, 0.2560461 , 0.30644165, 0.30051221])

# Task 3

In [4]:
df2 = pd.read_csv("/Users/matveyspiridonov/Downloads/wine.data", header=None)
df2.columns=[i for i in range(14)]
df2

0      1     2     3     4    5     6     7     8     9      10    11  \
0     1  14.23  1.71  2.43  15.6  127  2.80  3.06  0.28  2.29   5.64  1.04   
1     1  13.20  1.78  2.14  11.2  100  2.65  2.76  0.26  1.28   4.38  1.05   
2     1  13.16  2.36  2.67  18.6  101  2.80  3.24  0.30  2.81   5.68  1.03   
3     1  14.37  1.95  2.50  16.8  113  3.85  3.49  0.24  2.18   7.80  0.86   
4     1  13.24  2.59  2.87  21.0  118  2.80  2.69  0.39  1.82   4.32  1.04   
..   ..    ...   ...   ...   ...  ...   ...   ...   ...   ...    ...   ...   
173   3  13.71  5.65  2.45  20.5   95  1.68  0.61  0.52  1.06   7.70  0.64   
174   3  13.40  3.91  2.48  23.0  102  1.80  0.75  0.43  1.41   7.30  0.70   
175   3  13.27  4.28  2.26  20.0  120  1.59  0.69  0.43  1.35  10.20  0.59   
176   3  13.17  2.59  2.37  20.0  120  1.65  0.68  0.53  1.46   9.30  0.60   
177   3  14.13  4.10  2.74  24.5   96  2.05  0.76  0.56  1.35   9.20  0.61   

       12    13  
0    3.92  1065  
1    3.40  1050  
2    3.17  1185  
3    3.45  1480  
4    2.93   735  
..    ...   ...  
173  1.74   740  
174  1.56   750  
175  1.56   835  
176  1.62   840  
177  1.60   560  

[178 rows x 14 columns]

In [41]:
from sklearn.neighbors import KNeighborsClassifier as KNN
from sklearn.neighbors import KNeighborsRegressor as KNNR
from sklearn.model_selection import KFold
from sklearn.metrics import accuracy_score as accuracy
from sklearn.model_selection import cross_val_score
from sklearn.preprocessing import scale
import sklearn.datasets

In [8]:
split = KFold(n_splits = 5, shuffle = True, random_state = 42)

In [21]:
for i in range(1, 50):
    crs = cross_val_score(KNN(n_neighbors = i), df2.drop(0, axis = 1), df2[0], cv = split,scoring = 'accuracy')
    print(crs, crs.mean())

[0.77777778 0.66666667 0.72222222 0.71428571 0.77142857] 0.7304761904761905
[0.72222222 0.63888889 0.69444444 0.57142857 0.68571429] 0.6625396825396825
[0.80555556 0.61111111 0.63888889 0.65714286 0.82857143] 0.7082539682539682
[0.75       0.52777778 0.61111111 0.65714286 0.74285714] 0.6577777777777778
[0.72222222 0.61111111 0.61111111 0.68571429 0.74285714] 0.6746031746031746
[0.72222222 0.63888889 0.63888889 0.68571429 0.68571429] 0.6742857142857144
[0.69444444 0.58333333 0.72222222 0.68571429 0.71428571] 0.68
[0.72222222 0.61111111 0.66666667 0.65714286 0.74285714] 0.6799999999999999
[0.72222222 0.63888889 0.72222222 0.68571429 0.74285714] 0.7023809523809523
[0.72222222 0.61111111 0.63888889 0.68571429 0.74285714] 0.6801587301587302
[0.75       0.63888889 0.66666667 0.71428571 0.74285714] 0.7025396825396826
[0.72222222 0.66666667 0.69444444 0.68571429 0.71428571] 0.6966666666666667
[0.72222222 0.69444444 0.66666667 0.65714286 0.71428571] 0.6909523809523809
[0.72222222 0.66666667 0.7

In [30]:
X = scale(df2.drop(0, axis = 1))

In [32]:
for i in range(1, 50):
    crs = cross_val_score(KNN(n_neighbors = i), X, df2[0], cv = split,scoring = 'accuracy')
    print(crs, crs.mean(), i)

[0.94444444 0.94444444 0.91666667 0.97142857 0.94285714] 0.943968253968254 1
[0.94444444 0.88888889 0.91666667 0.97142857 0.94285714] 0.9328571428571429 2
[0.94444444 0.94444444 0.97222222 0.97142857 0.94285714] 0.9550793650793651 3
[0.94444444 0.91666667 0.94444444 0.94285714 0.94285714] 0.9382539682539683 4
[0.94444444 0.94444444 0.97222222 0.91428571 0.97142857] 0.9493650793650794 5
[0.94444444 0.91666667 0.97222222 0.97142857 0.94285714] 0.9495238095238095 6
[0.94444444 0.91666667 0.97222222 0.94285714 0.97142857] 0.9495238095238095 7
[0.94444444 0.91666667 0.97222222 0.97142857 0.97142857] 0.9552380952380952 8
[0.94444444 0.94444444 0.97222222 0.94285714 1.        ] 0.9607936507936508 9
[0.94444444 0.94444444 0.97222222 0.97142857 0.97142857] 0.9607936507936508 10
[0.94444444 0.94444444 0.94444444 0.97142857 1.        ] 0.9609523809523809 11
[0.97222222 0.91666667 0.94444444 0.97142857 0.97142857] 0.9552380952380952 12
[0.94444444 0.94444444 0.94444444 0.91428571 1.        ] 0.949

In [37]:
df3 = sklearn.datasets.load_boston()
df3

{'data': array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 1.5300e+01, 3.9690e+02,
         4.9800e+00],
        [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9690e+02,
         9.1400e+00],
        [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9283e+02,
         4.0300e+00],
        ...,
        [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
         5.6400e+00],
        [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9345e+02,
         6.4800e+00],
        [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
         7.8800e+00]]),
 'target': array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9, 15. ,
        18.9, 21.7, 20.4, 18.2, 19.9, 23.1, 17.5, 20.2, 18.2, 13.6, 19.6,
        15.2, 14.5, 15.6, 13.9, 16.6, 14.8, 18.4, 21. , 12.7, 14.5, 13.2,
        13.1, 13.5, 18.9, 20. , 21. , 24.7, 30.8, 34.9, 26.6, 25.3, 24.7,
        21.2, 19.3, 20. , 16.6, 14.4, 19.4, 19.7, 20.5, 25. , 23.4, 18.9,
        35.4, 24.7, 3

In [38]:
X_ = df3['data']
X_

array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 1.5300e+01, 3.9690e+02,
        4.9800e+00],
       [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9690e+02,
        9.1400e+00],
       [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9283e+02,
        4.0300e+00],
       ...,
       [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        5.6400e+00],
       [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9345e+02,
        6.4800e+00],
       [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        7.8800e+00]])

In [39]:
y_ = df3['target']
y_

array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9, 15. ,
       18.9, 21.7, 20.4, 18.2, 19.9, 23.1, 17.5, 20.2, 18.2, 13.6, 19.6,
       15.2, 14.5, 15.6, 13.9, 16.6, 14.8, 18.4, 21. , 12.7, 14.5, 13.2,
       13.1, 13.5, 18.9, 20. , 21. , 24.7, 30.8, 34.9, 26.6, 25.3, 24.7,
       21.2, 19.3, 20. , 16.6, 14.4, 19.4, 19.7, 20.5, 25. , 23.4, 18.9,
       35.4, 24.7, 31.6, 23.3, 19.6, 18.7, 16. , 22.2, 25. , 33. , 23.5,
       19.4, 22. , 17.4, 20.9, 24.2, 21.7, 22.8, 23.4, 24.1, 21.4, 20. ,
       20.8, 21.2, 20.3, 28. , 23.9, 24.8, 22.9, 23.9, 26.6, 22.5, 22.2,
       23.6, 28.7, 22.6, 22. , 22.9, 25. , 20.6, 28.4, 21.4, 38.7, 43.8,
       33.2, 27.5, 26.5, 18.6, 19.3, 20.1, 19.5, 19.5, 20.4, 19.8, 19.4,
       21.7, 22.8, 18.8, 18.7, 18.5, 18.3, 21.2, 19.2, 20.4, 19.3, 22. ,
       20.3, 20.5, 17.3, 18.8, 21.4, 15.7, 16.2, 18. , 14.3, 19.2, 19.6,
       23. , 18.4, 15.6, 18.1, 17.4, 17.1, 13.3, 17.8, 14. , 14.4, 13.4,
       15.6, 11.8, 13.8, 15.6, 14.6, 17.8, 15.4, 21

In [40]:
X_ = scale(X_)

In [46]:
a = []
for i in np.linspace(1,10,200):
    crs = cross_val_score(KNNR(n_neighbors=5, weights='distance', metric = 'minkowski', p = i), X_, y_, cv = split, scoring='neg_mean_squared_error')
    a.append([crs.mean(), i])
    print(crs, crs.mean(), i)

[-20.21899107 -12.49567191 -17.22129105 -11.83373336 -18.38354627] -16.030646734221644 1.0
[-20.22607648 -12.57429075 -17.43647464 -12.07494178 -19.72740989] -16.40783870832999 1.0452261306532664
[-20.13329413 -12.65479751 -17.68764499 -11.92277511 -19.45497299] -16.370696947059045 1.0904522613065326
[-20.20518452 -12.96135285 -17.65835017 -11.91533174 -19.48836227] -16.445716308439433 1.135678391959799
[-19.93196196 -12.90136373 -18.02078301 -11.95450061 -19.56667956] -16.475057773399403 1.1809045226130652
[-19.80364184 -12.87447015 -17.93740291 -12.11406897 -19.90257779] -16.526432329318258 1.2261306532663316
[-19.92462793 -13.24345009 -17.97716386 -12.09748856 -19.94081629] -16.636709345898257 1.271356783919598
[-19.85066747 -13.80890388 -17.68416088 -12.66957076 -20.10781828] -16.82422425426731 1.3165829145728645
[-19.87699063 -13.94042247 -17.88657538 -12.68019921 -19.98685759] -16.874209056598744 1.3618090452261307
[-19.86064833 -13.98675631 -19.19762903 -12.65965632 -19.9198041 

[-19.15178857 -16.94566396 -21.88504527 -19.68923426 -20.21548573] -19.577443558088486 4.708542713567839
[-19.25059484 -16.94481684 -21.98280056 -19.96030832 -20.22610983] -19.67292607910183 4.7537688442211055
[-19.25238905 -16.94863731 -22.04524051 -19.96598558 -20.20894036] -19.68423856503004 4.798994974874372
[-19.25414986 -17.05918269 -22.12673024 -19.97152241 -20.24551179] -19.731419398024357 4.844221105527638
[-19.25429529 -16.99742048 -22.135899   -19.97816667 -20.30106408] -19.73336910414023 4.889447236180905
[-19.25530246 -17.0030907  -22.14143236 -19.98351586 -20.31014024] -19.738696325445968 4.934673366834171
[-19.38603187 -17.00864945 -22.14685605 -19.98873549 -20.31966937] -19.769988446644323 4.9798994974874375
[-19.38780425 -16.84710692 -22.07796251 -19.90949373 -20.12932289] -19.670338059212803 5.025125628140704
[-19.41892321 -16.85712051 -22.08328023 -19.88640317 -20.12584257] -19.67431393586822 5.07035175879397
[-19.3173279  -16.85728533 -21.92721944 -19.92797021 -20.1

[-20.47210895 -19.55269571 -23.96033226 -20.19150408 -20.86198232] -21.007724663240943 8.326633165829147
[-20.47244452 -19.55394067 -23.96201188 -20.19235963 -20.86436979] -21.009025299728833 8.371859296482413
[-20.47277649 -19.55516532 -23.96366767 -20.20248189 -20.86671971] -21.01216221477924 8.417085427135678
[-20.49151119 -19.55637005 -23.96530003 -20.20331153 -20.86903274] -21.01710510789645 8.462311557788945
[-20.47548487 -19.55755524 -23.96690941 -20.20412732 -20.87083827] -21.014983021890455 8.507537688442211
[-20.47579683 -19.55872126 -23.96849621 -20.20492956 -20.8730963 ] -21.016208031732354 8.552763819095478
[-20.45101492 -19.55986849 -23.97006083 -20.20571853 -20.87531922] -21.012396399713907 8.597989949748744
[-20.45202774 -19.56099729 -23.97160367 -20.20649452 -20.87404902] -21.013034449348474 8.64321608040201
[-20.45234378 -19.562108   -23.98335367 -20.20725781 -20.87620674] -21.016253998579874 8.688442211055277
[-20.44387114 -19.56320098 -24.00026339 -20.14487002 -20.8

In [48]:
a.sort(key=lambda x: x[0])
a

[[-21.112469472718395, 9.50251256281407],
 [-21.111525199609268, 9.457286432160805],
 [-21.110567605644725, 9.412060301507537],
 [-21.1058426886423, 9.366834170854272],
 [-21.104978219205865, 9.321608040201005],
 [-21.089703307229723, 10.0],
 [-21.08381944188997, 9.954773869346734],
 [-21.083360868317154, 9.095477386934673],
 [-21.08297912459029, 9.909547738693467],
 [-21.08212737263425, 9.864321608040202],
 [-21.08126399272046, 9.819095477386934],
 [-21.080059124071415, 9.27638190954774],
 [-21.079037165101987, 9.231155778894472],
 [-21.078517076081955, 9.185929648241206],
 [-21.07749767601852, 9.773869346733669],
 [-21.077465796576227, 9.14070351758794],
 [-21.07661546615345, 9.728643216080402],
 [-21.075721076535178, 9.683417085427136],
 [-21.074814298351164, 9.63819095477387],
 [-21.071034728064937, 8.055276381909547],
 [-21.068482443357823, 7.964824120603016],
 [-21.06818327983064, 8.010050251256281],
 [-21.06698490725231, 7.919597989949749],
 [-21.066511767241785, 9.5929648241206